# .github/workflows/dispatch_execute.yml
name: Ejecutar script en Snowflake tras merge

on:
  push:
    branches:
      - main  # Solo cuando hay un push en main (típico tras merge)
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar SnowSQL (por dpkg)
        run: |
          sudo apt-get update
          curl -L -o snowsql-1.2.24.deb https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24.deb
          sudo dpkg -i snowsql-1.2.24.deb

      - name: Ejecutar script SQL en Snowflake
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
        run: |
          ./snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PWD -f path/a/tu/script.sql
