# .github/workflows/dispatch_execute.yml
name: Ejecutar scripts en Snowflake al hacer merge

on:
  push:
    branches:
      - main

jobs:
  ejecutar_en_snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Snowflake CLI moderna
        run: |
          python3 -m pip install --upgrade pip
          pip install --user snowflake-cli-labs

      - name: Ejecutar todos los .sql con snow
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWSQL_PWD }}
          SNOWFLAKE_ROLE: SYSADMIN             # o el que necesites
          SNOWFLAKE_WAREHOUSE: COMPUTE_WH      # ajusta al tuyo
          SNOWFLAKE_DATABASE: DEV_LEARN_DWH
          SNOWFLAKE_SCHEMA: TEST_SCHEMA
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          
          echo "🟢 Ejecutando scripts .sql..."
          for file in $(find . -name "*.sql" | sort); do
            echo "⏳ Ejecutando: $file"
            snow sql run --file "$file"
          done
