# .github/workflows/dispatch_execute.yml
name: Ejecutar scripts en Snowflake al hacer merge

on:
  push:
    branches:
      - main

jobs:
  ejecutar_en_snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Snowflake CLI (snowcli)
        run: |
          python3 -m pip install --upgrade pip
          pip install snowflake-cli-labs

      - name: Configurar conexión y ejecutar scripts
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWSQL_PWD }}
        run: |
          snowcli config add --account $SNOWFLAKE_ACCOUNT --user $SNOWFLAKE_USER --password $SNOWFLAKE_PASSWORD --alias ci

          echo "🟢 Ejecutando scripts .sql modificados..."
          for file in $(find . -name "*.sql" | sort); do
            echo "⏳ Ejecutando: $file"
            snowcli sql run --config ci --file "$file"
          done
