# .github/workflows/dispatch_execute.yml
name: Ejecutar scripts en Snowflake al hacer merge

on:
  push:
    branches:
      - main

jobs:
  ejecutar_en_snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Snowflake CLI (snow)
        run: |
          python3 -m pip install --upgrade pip
          pip install --user snowflake-cli-labs

      - name: Ejecutar scripts .sql en orden
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWSQL_PWD }}
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          
          snow config init --account $SNOWFLAKE_ACCOUNT --user $SNOWFLAKE_USER --password $SNOWFLAKE_PASSWORD --non-interactive --default

          echo "🟢 Ejecutando scripts .sql..."
          for file in $(find . -name "*.sql" | sort); do
            echo "⏳ Ejecutando: $file"
            snow sql run --file "$file"
          done
