name: Ejecutar en Snowflake

on:
  push:
    branches: [main]

jobs:
  ejecutar_sql:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Instalar Snowflake Connector
        run: |
          python3 -m pip install --upgrade pip
          pip install snowflake-connector-python

      - name: Ejecutar SQL
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
        run: |
          python3 TB_SNOWFLAKE_1_0_0.sql
