# .github/workflows/dispatch_execute.yml
name: Ejecutar script en Snowflake tras merge

on:
  push:
    branches:
      - main  # Solo cuando hay un push en main (típico tras merge)
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar SnowSQL
        run: |
          sudo apt-get update && sudo apt-get install -y curl unzip
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24-linux_x86_64.bash
          bash snowsql-1.2.24-linux_x86_64.bash

      - name: Ejecutar script SQL en Snowflake
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
        run: |
          ./snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PWD -f path/a/tu/script.sql
